# Site settings
title: Luis Kaiser
author: Luis Kaiser
email: lkaiser (at) utexas.edu
description: >
   Luis Kaiser is a PhD student at the Oden Institute, UT Austin, working on AI for science and applied mathematics. He builds agentic AI systems for scientific discovery at Google [X].
url: "https://luiskaiser.com"
baseurl: ""
lang: en-US
logo: /images/profile/lkaiser_profile.jpeg
production_url: "https://luiskaiser.com"
github_username: utkaiser

social:
  name: Luis Kaiser
  links:
    - https://x.com/luiskaiser_
    - https://www.linkedin.com/in/luiskaiser/
    - https://scholar.google.com/citations?user=AB4exREAAAAJ&hl=en
    - https://www.researchgate.net/profile/Luis-Kaiser-6?ev=prf_overview
    - https://github.com/utkaiser

twitter:
  username: luiskaiser_

permalink: /blog/:year/:month/:title.html

sass:
  style: compressed

collections:
  publications:
    output: false

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
